"""
Parse AI markdown into structured KnowledgeDocument.
"""

from __future__ import annotations

import re

from ai.schemas import (
    KnowledgeDocument,
    VideoInfo,
)


class MarkdownParser:
    """
    Parse markdown generated by AI.
    """

    def __init__(self):

        self.section_pattern = re.compile(
            r"^#{2,3}\s*(.+?)\s*$",
            re.MULTILINE,
        )

    # ---------------------------------------------------------
    # public
    # ---------------------------------------------------------

    def parse(
        self,
        markdown: str,
    ) -> KnowledgeDocument:

        markdown = markdown.replace("\r\n", "\n")

        doc = KnowledgeDocument()

        doc.title = self._parse_title(markdown)

        sections = self._split_sections(markdown)

        for name, body in sections.items():

            key = self._normalize(name)

            # ---------------- Video ----------------

            if "视频信息" in key:

                doc.video_info = self._parse_video_info(body)

            # ---------------- Viewpoints ----------------

            elif (
                "核心观点" in key
                or "主要观点" in key
                or "观点" in key
            ):

                doc.viewpoints.extend(
                    self._parse_list(body)
                )

            # ---------------- Keywords ----------------

            elif (
                "关键词" in key
                or "关键字" in key
                or "标签" in key
            ):

                doc.keywords.extend(
                    self._parse_keywords(body)
                )

            # ---------------- Content ----------------

            elif (
                "内容整理" in key
                or "内容总结" in key
                or "整理" in key
                or "总结" in key
                or "正文" in key
            ):

                doc.contents.extend(
                    self._parse_content(body)
                )

            # ---------------- Quotes ----------------

            elif (
                "金句" in key
                or "经典语录" in key
                or "语录" in key
                or "精彩语句" in key
            ):

                doc.quotes.extend(
                    self._parse_list(body)
                )

        return doc

    # ---------------------------------------------------------
    # title
    # ---------------------------------------------------------

    def _parse_title(
        self,
        markdown: str,
    ) -> str:

        for line in markdown.splitlines():

            line = line.strip()

            if line.startswith("# "):

                return line[2:].strip()

        return ""

    # ---------------------------------------------------------
    # section split
    # ---------------------------------------------------------

    def _split_sections(
        self,
        markdown: str,
    ) -> dict[str, str]:

        matches = list(
            self.section_pattern.finditer(markdown)
        )

        result = {}

        for i, match in enumerate(matches):

            name = match.group(1).strip()

            start = match.end()

            if i == len(matches) - 1:

                end = len(markdown)

            else:

                end = matches[i + 1].start()

            result[name] = markdown[start:end].strip()

        return result

    # ---------------------------------------------------------
    # normalize
    # ---------------------------------------------------------

    def _normalize(
        self,
        title: str,
    ) -> str:

        title = title.strip()

        title = title.replace("：", "")
        title = title.replace(":", "")
        title = title.replace("**", "")

        # 去掉常见编号
        title = re.sub(
            r"^[\s]*(第?\d+[章节部分]?[、.．:]?|[一二三四五六七八九十]+[、.．:]?|[①②③④⑤⑥⑦⑧⑨⑩])[ ]*",
            "",
            title,
        )

        return title.strip()
    # ---------------------------------------------------------
    # video info
    # ---------------------------------------------------------

    def _parse_video_info(
        self,
        text: str,
    ) -> VideoInfo:

        info = VideoInfo()

        for line in text.splitlines():

            line = line.strip()

            if not line:
                continue

            if "http" in line:

                match = re.search(
                    r"https?://\S+",
                    line,
                )

                if match:
                    info.url = match.group(0)

            elif "采集时间" in line:

                value = re.split(
                    r"[：:]",
                    line,
                    maxsplit=1,
                )

                if len(value) > 1:

                    info.collected_at = value[1].strip()

        return info

    # ---------------------------------------------------------
    # list
    # ---------------------------------------------------------

    def _parse_list(
        self,
        text: str,
    ) -> list[str]:

        result = []

        for line in text.splitlines():

            line = line.strip()

            if not line:
                continue

            line = re.sub(
                r"^[-*•]\s*",
                "",
                line,
            )

            line = re.sub(
                r"^\d+[.)、]\s*",
                "",
                line,
            )

            line = re.sub(
                r"^[①②③④⑤⑥⑦⑧⑨⑩]\s*",
                "",
                line,
            )

            line = line.strip()

            if line:

                result.append(line)

        return result

    # ---------------------------------------------------------
    # keywords
    # ---------------------------------------------------------

    def _parse_keywords(
        self,
        text: str,
    ) -> list[str]:

        result = []

        for line in text.splitlines():

            line = line.strip()

            if not line:
                continue

            line = re.sub(
                r"^[-*•]\s*",
                "",
                line,
            )

            line = re.sub(
                r"^\d+[.)、]\s*",
                "",
                line,
            )

            line = line.replace("，", ",")

            for item in line.split(","):

                item = item.strip()

                if item:

                    result.append(item)

        return result

    # ---------------------------------------------------------
    # content
    # ---------------------------------------------------------

    def _parse_content(
        self,
        text: str,
    ) -> list[str]:

        paragraphs = []

        current = []

        for line in text.splitlines():

            line = line.rstrip()

            if not line.strip():

                if current:

                    paragraphs.append(
                        "\n".join(current).strip()
                    )

                    current = []

                continue

            current.append(line)

        if current:

            paragraphs.append(
                "\n".join(current).strip()
            )

        return paragraphs