"""
Parse AI markdown into structured KnowledgeDocument.
"""

from __future__ import annotations

import re

from ai.schemas import (
    KnowledgeDocument,
    VideoInfo,
)


class MarkdownParser:
    """
    Parse markdown generated by AI.
    """

    def __init__(self):

        self.section_pattern = re.compile(
            r"^##\s*(.+?)\s*$",
            re.MULTILINE,
        )

    # ---------------------------------------------------------
    # public
    # ---------------------------------------------------------

    def parse(
        self,
        markdown: str,
    ) -> KnowledgeDocument:

        markdown = markdown.replace("\r\n", "\n")

        doc = KnowledgeDocument()

        doc.title = self._parse_title(markdown)

        sections = self._split_sections(markdown)

        for name, body in sections.items():

            key = self._normalize(name)

            if key == "视频信息":

                doc.video_info = self._parse_video_info(body)

            elif key == "核心观点":

                doc.viewpoints = self._parse_list(body)

            elif key == "关键词":

                doc.keywords = self._parse_keywords(body)

            elif key == "内容整理":

                doc.contents = self._parse_content(body)

            elif key == "金句":

                doc.quotes = self._parse_list(body)

        return doc

    # ---------------------------------------------------------
    # title
    # ---------------------------------------------------------

    def _parse_title(
        self,
        markdown: str,
    ) -> str:

        for line in markdown.splitlines():

            line = line.strip()

            if line.startswith("# "):

                return line[2:].strip()

        return ""

    # ---------------------------------------------------------
    # section split
    # ---------------------------------------------------------

    def _split_sections(
        self,
        markdown: str,
    ) -> dict[str, str]:

        matches = list(
            self.section_pattern.finditer(markdown)
        )

        result = {}

        for i, m in enumerate(matches):

            name = m.group(1).strip()

            start = m.end()

            if i == len(matches) - 1:

                end = len(markdown)

            else:

                end = matches[i + 1].start()

            result[name] = markdown[start:end].strip()

        return result

    # ---------------------------------------------------------
    # normalize
    # ---------------------------------------------------------

    def _normalize(
        self,
        title: str,
    ) -> str:

        title = title.strip()

        title = title.replace("：", "")

        title = title.replace(":", "")

        return title

    # ---------------------------------------------------------
    # video info
    # ---------------------------------------------------------

    def _parse_video_info(
        self,
        text: str,
    ) -> VideoInfo:

        info = VideoInfo()

        for line in text.splitlines():

            line = line.strip()

            if not line:

                continue

            if "http" in line:

                info.url = line.split()[-1]

            elif "采集时间" in line:

                value = line.split("：")[-1]

                value = value.split(":")[-1]

                info.collected_at = value.strip()

        return info

    # ---------------------------------------------------------
    # list
    # ---------------------------------------------------------

    def _parse_list(
        self,
        text: str,
    ) -> list[str]:

        result = []

        for line in text.splitlines():

            line = line.strip()

            if not line:

                continue

            line = re.sub(
                r"^[-*•]\s*",
                "",
                line,
            )

            line = re.sub(
                r"^\d+[.)、]\s*",
                "",
                line,
            )

            if line:

                result.append(line)

        return result

    # ---------------------------------------------------------
    # keywords
    # ---------------------------------------------------------

    def _parse_keywords(
        self,
        text: str,
    ) -> list[str]:

        text = text.replace("\n", ",")

        text = text.replace("，", ",")

        result = []

        for item in text.split(","):

            item = item.strip()

            if item:

                result.append(item)

        return result

    # ---------------------------------------------------------
    # content
    # ---------------------------------------------------------

    def _parse_content(
        self,
        text: str,
    ) -> list[str]:

        paragraphs = []

        for p in text.split("\n\n"):

            p = p.strip()

            if p:

                paragraphs.append(p)

        return paragraphs